sudo: required
dist: xenial
language: python
matrix:
  include:
  - os: linux
    python: '3.5'
  - os: linux
    python: '3.6'
  - os: linux
    python: '3.7'
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.7.5
  - os: linux
    python: '3.7'
    env: SNOWFLAKE_AZURE=true
  - os: linux
    python: '3.7'
    env: SNOWFLAKE_GCP=true
install:
- "./ci/install.sh"
script:
- "./ci/run_travis.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: dFpjLRaP1GcqHB449/6tca+63dZk8iAyD1afM5GK74HiO4dNAwGlONFY0KNnFVIkVDO7XJu0DpbNL/gXZy+EZ2WKis/vcwb2FhkYoiSJ1oZZ6fr/QbwyVZMH1y5L/gxipb5+MlBZyOQGX+9OZNQaGaSRd8kygOX8maBGm3IZFsNhjq6RwbBTLP3Zr8cJ+xrkrj7r413jKy/0xVKVr234gl4VU5IN2k6ovT4KBTyRMhwI5ImWL4ZCiJ7cZbfuLCaOuCdtXTzxU32O0gjbDV1D6ryezVfjtKzdUSLzb+71nT444xXq1OFDWxvODWdE0MBYQEdqHsbhg/Bj/Gp+i1smH4s5wgZ1r7TQMX/oUnsKSkCx0NphS57FKTiYdMGl5o78JuFNf02o2CYux6Zv0LEky/EhsP1o1vclm8LKZiHERZF6fALrOVDTibPw8wKSjHK8NkcglR2d/9X3DOvddxwfN7oJjt/cjIkkDTtYE4WdOZ06EUVzSgUVjaj8JqdlOaWqYBsJRzb0b2uWfU8L5yJ9DJemmWxhhsilEhD7SGPOphuGjHVXa2YivXxl7lO7pJgWWWG37T+XYhbGxIusSP+VwSOcP2LykQbg0S964344dpk2T/CKX0JpeBPYhRoRFvOLBt7HsItT2d9kbSYVJ07xuRkMUMxN7jm4dl+Pxsy3gxs=
  - secure: iFgCTUE6izlHLYSJuDFpGwj+wI6yY7zjkGXLME7W0RHCQk1xjwN9o0EwsEhE0+/WPlxn4SrXI7gKp+2+z94ImtZY7MiM1qOzUaS0FrrwoMPpvIb3e8csGfI5mKbiKOoZNCMTD3wdxc+sohZ5GHc/qeUvNw6WLJL15V8m+w/qPeaGTj6mC/Oys18d91uz2WD9erIeVx0eQx653lL+pd+/D4dPk43/Jy19vLmliie3sragjcbS9lRdRvlp8WDJ+y41D5EPRai+F1Y5CWP0rKDV3vrmdy50DYrzu8X9kTCcXq1CjS90o/Wb+E640awhlvjHw4ocDcNAfZv5BQoZ2YcqZWhdSIICGiei70NMOdCdWyTHmLgFu+7TqGQdc3mtaPWcC1BQ28urWcWsivjj83aCxJkshTdfpaTV6xfnYaJFTm6+oa2Yq2wDadhjzA4OAxtP9FIKurfhE6zaSGJUiFtXyCAEKUwQKGkfe6Dw3JmfusxPlDYaYu0mD9g+OJn1jcoVeuwwVf3HLoW/dNp+FWDsnroImMAc1D0eiwgMTovuSmpPFD+zi19yNpCNlJcFIfH85JxUj8q44+yiEFrdTD1tj5SgXBp7fOGW+wH8l5u+rGKEGiL1j8c5uYEahRW/QhmrjHZfgcZiKz4VKX5DmRysCbD0qWYaUZBZQkFZwKCZUc0=
  - secure: CE+6ke+lNgd/rrxGYAw0UzYvvDcfm7+XlNBMTbDlQyI3L5ulxAgNZNvVI+18IjonYqR3QOisXqS9EmsIQSUzCZ9+Z1vo9Fi1CP5oYHLk9qfi59HUXFkCOOcgzNTqHUm589Juao8pFuJiEXbhqtAv4nwn3WzdDwmqB5tCQj2/g9blYg2vL3dxp6yw1Ruet7gCt8+/X+wzgaBMoPW+iPbW1GK6qisU1uJy1GKU3f+eC93n381IQIzrCBesmmaU33R3d1ntkUgz8ln/o7Par9gPY+apiewG5pb9gN+PCd7wpFKOS4ldNRRdKTg0MFBugoqLm67yMwI6NECNZ9QXD7JuKH7tNuiBMUTo2Zze0W1VdAbrh+p5BWP7mq7weUXC05fbqUSeBrovsYIegNtdlxP8eDAmSm8ePavl64Mw6dpKo8uuynLA45Ngx4FP+ghiogsvXwplnijDjNTCrwhY3/kiDBjXxaROnFYk6UDwMZRxpxQjqEdyIw8+Pv/XyrDRbvwj7XBhJDc1shUXva25zR/4LpwiI4pw/X9/3ttDjk7KSY6rSdJzsaQANy5Xbl+9E7CdJJ2Tfj6D7sUKxi/3LRSrBJRh/Hze3pGreSuX2saY57dTIY1HFDJdBjL2RB0LmkTkkzlA8xPV7FnmZqhEn6G6mGXNfcQawJdYIIp78AbgHsI=
