name: Run custom pytest

on:
  push:

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cloud-provider: [aws, azure, gcp]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup parameters file
        shell: bash
        env:
          PARAMETERS_SECRET: ${{ secrets.PARAMETERS_SECRET }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PARAMETERS_SECRET" \
          .github/workflows/parameters/public/parameters_${{ matrix.cloud-provider }}.py.gpg > test/parameters.py
      - name: Setup private key file
        shell: bash
        env:
          PYTHON_PRIVATE_KEY_SECRET: ${{ secrets.PYTHON_PRIVATE_KEY_SECRET }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PYTHON_PRIVATE_KEY_SECRET" \
          .github/workflows/parameters/public/rsa_keys/rsa_key_python_${{ matrix.cloud-provider }}.p8.gpg > test/rsa_key_python_${{ matrix.cloud-provider }}.p8

#      - name: Setup private key file
#        shell: bash
#        env:
#          PARAMETERS_SECRET: ${{ secrets.PARAMETERS_SECRET }}
#        run: |
#          gpg --quiet --batch --yes --decrypt --passphrase="$PARAMETERS_SECRET" \
#          .github/workflows/parameters/public/rsa_keys/rsa_key_python_${{ matrix.cloud-provider }}.p8.gpg > test/rsa_key_python_${{ matrix.cloud-provider }}.p8

      - name: Install dependencies
        run: |
          python -m pip install ".[development,aio,secure-local-storage]"

      - name: Run pytest
        run: |
          pytest -vvv -k "file_permission" .
