name: Snyk Issue

on:
  schedule:
    - cron: '* */12 * * *'

concurrency: snyk-issue

jobs:
  whitesource:
    runs-on: ubuntu-latest
    steps:
    - name: checkout action
      uses: actions/checkout@v3
      with:
        repository: snowflakedb/whitesource-actions
        token: ${{ secrets.WHITESOURCE_ACTION_TOKEN }}
        path: whitesource-actions
    - name: set-env
      run: echo "REPO=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
    - name: Jira Creation
      uses: ./whitesource-actions/snyk-issue
      with:
        snyk_org: ${{ secrets.SNYK_ORG_ID_PUBLIC_REPO }}
        snyk_token:  ${{ secrets.SNYK_GITHUB_INTEGRATION_TOKEN_PUBLIC_REPO }}
        jira_token: ${{ secrets.JIRA_TOKEN_PUBLIC_REPO }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

