name: snyk-pr
on:
  pull_request:
    branches:
      - main
jobs:
  whitesource:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'sfc-gh-snyk-sca-sa' }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: checkout action
      uses: actions/checkout@v3
      with:
        repository: snowflakedb/whitesource-actions
        token: ${{ secrets.whitesource_action_token }}
        path: whitesource-actions

    - name: snyk pr
      uses: ./whitesource-actions/snyk-pr
      env:
        pr_title: ${{ github.event.pull_request.title }}
      with:
        jira_token: ${{ secrets.jira_token_public_repo }}
        gh_token: ${{ secrets.github_token }}
        amend: false
