name: Snyk Issue

on:
  issues:
    types: [opened, reopened]

concurrency: snyk-issue

jobs:
  whitesource:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.user.login == 'sfc-gh-snyk-sca-sa' }}
    steps:
    - name: checkout action
      uses: actions/checkout@v2
      with:
        repository: snowflakedb/whitesource-actions
        token: ${{ secrets.WHITESOURCE_ACTION_TOKEN }}
        path: whitesource-actions

    - name: Jira Creation
      uses: ./whitesource-actions/snyk-issue
      with:
        jira_token: ${{ secrets.JIRA_TOKEN }}
        gh_token: ${{ secrets.GITHUB_TOKEN }}
